spring:
  quartz:
    auto-startup: true
    job-store-type: memory # Если нужно использовать память (по умолчанию)
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10
          jobStore:
            class: org.quartz.simpl.RAMJobStore
  datasource:
    url: jdbc:postgresql://localhost:5432/mldb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Отключаем автоматическое создание схемы Hibernate, так как используем Liquibase
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false


minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: my-bucket
  pool-size: 5

